.PHONY: all
all:
	g++ -o np_simple np_simple.cpp
	g++ -o np_single_proc np_single_proc.cpp
	g++ -o np_multi_proc np_multi_proc.cpp -lpthread 
clean:
	rm np_simple
	rm np_single_proc
	rm np_multi_proc
